### ISSUE TITLE
Only addon files are linted when using `ember test`

### ISSUE THREAD

**Issue by rogatty** [rwjblue/ember-cli-template-lint#118]
I've used `ember install ember-cli-template-lint` and modified `.template-lintrc` to look like this:
```
module.exports = {
    rules: {
        'self-closing-void-elements': true,
    }
};
```

When I use `ember template-lint:print-failing` I get a nice list of all templates in my app that break the rule. No addon files are inspected.

When I use `ember test` or `ember build` I get:
```
self-closing-void-elements: Self-closing a void element is redundant(modules/ember-cli-head/templates/components/head-layout):
`<meta name="ember-cli-head-start" />`
self-closing-void-elements: Self-closing a void element is redundant(modules/ember-cli-head/templates/components/head-layout @ L1:C52):
`<meta name="ember-cli-head-end" />`
===== 2 Template Linting Errors
```
Which ignored in-app templates and instead linted the ones from `ember-cli-head` addon.

I've tried to debug it and found that `lintTree(type, tree)` hook in https://github.com/rwjblue/ember-cli-template-lint/blob/master/index.js#L18 is called only twice and for this specific addon with `type === 'addon'` and `type === 'templates`.
After digging in `ember-cli` I've found that `lintTree` is only mentioned in the addon context:
- https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L566
- https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L735

Does it mean that `ember-cli-template-lint` is designed for addons only? I don't see any info about this and it doesn't really make sense given that `ember template-lint:print-failing` lints the app templates.
Did I misconfigure something? You can check my setup at https://github.com/Wikia/mercury/tree/ember-cli-template-lint/front/main

**Comment by rwjblue** [comment]
I submitted https://github.com/ronco/ember-cli-head/pull/6 a while back to fix the issue with ember-cli-head (you will have to update to the latest version to get that fix).

> Does it mean that ember-cli-template-lint is designed for addons only?

Absolutely not, this is primarily an app focused addon (though it should definitely continue to work in addons also).

> Did I misconfigure something? You can check my setup at https://github.com/Wikia/mercury/tree/ember-cli-template-lint/front/main

I'm not sure what is going on, I'll try to poke around in the repo tomorrow and see if anything stands out at me...

**Comment by rogatty** [comment]
I updated ember-cli-head and now `ember test` doesn't show any errors while `ember template-lint:print-failing` does.

Thanks for taking interest in this but if you won't have time for poking around, can you tell me if `lintTree()` hook should be called on the app templates tree? ember-cli code that I linked to doesn't suggest that. But if not then how is it supposed to work? :confused:

**Comment by rwjblue** [comment]
Both addons and apps get `lintTree('templates', tree)` called for them:

* https://github.com/ember-cli/ember-cli/blob/8e283569e185d11333c63c5a2542f42253b2d57c/lib/models/addon.js#L736
* https://github.com/ember-cli/ember-cli/blob/d98ebea76ecd5eca13b0b3aa48b39ef72c4e8316/lib/broccoli/ember-app.js#L1143

**Comment by rogatty** [comment]
Thanks, that helped! I didn't see the second one which is wrapped in `if (this.hinting)`. We have `hinting: false` set in `ember-cli-build.js` and it was the reason why template linter wasn't running.

Would be nice to have it described in README :) Anyway, I'm closing and thanks for help.

**Comment by rwjblue** [comment]
> Would be nice to have it described in README :) 

To be honest, I actually forgot about that flag 😝 .  I'd gladly accept a PR for it...
