### ISSUE TITLE
Add cache invalidation info to remove warnings

### ISSUE THREAD

**Issue by GavinJoyce** [rwjblue/ember-cli-template-lint#147]
<img width="816" alt="screen shot 2016-08-12 at 13 24 10" src="https://cloud.githubusercontent.com/assets/2526/17622235/edad0306-6090-11e6-96d7-1b2362d2d740.png">

**Comment by rwjblue** [comment]
Thanks for reporting! We need to add. `baseDir` function to the registry.add line in `index.js`.

**Comment by rwjblue** [comment]
Similar to https://github.com/offirgolan/ember-cp-validations/pull/305

**Comment by GavinJoyce** [comment]
Thanks, I'll cut a PR
