### ISSUE TITLE
RFC: add `template-lint` command

### ISSUE THREAD

**Issue by kellyselden** [rwjblue/ember-cli-template-lint#149]
Sister to https://github.com/ember-cli/ember-cli-eslint/issues/92

Running the linting without running the whole test suite may be beneficial. Returning an error code for failures may help for CIs. I'm not familiar with this codebase, but if it functions like eslint, you may be able to get faster results if you don't have to wait for a complete ember build.

**Comment by rwjblue** [comment]
We have a template-lint:print-failures command that already does most of the work. We could extract the commonalities and add a command specifically for exit codes.

**Comment by buschtoens** [comment]
`template-lint:print-failing`, not `template-lint:print-failures`-

**Comment by rwjblue** [comment]
Ahh, sorry about that, thanks for the correction.

**Comment by saverio-kantox** [comment]
Running over one single template would be even more beneficial, to integrate with pre-commit hooks that only check for modified files.

**Comment by rwjblue** [comment]
Yep, should be easy to add. The majority of the code is already written. Someone just has to put the pieces together...

**Comment by rwjblue** [comment]
Also, FWIW, I believe the actual implementation of this should be a binary in ember-template-lint (not this repo).

**Comment by vladucu** [comment]
Noticed the CLI support landed a while ago in `ember-template-lint`, any plans on a new release with update `ember-template-lint`? Or is that something else blocking this?

**Comment by rwjblue** [comment]
This landed in ember-template-lint@0.7.0
