### ISSUE TITLE
Add possibility to disable temlate-lint

### ISSUE THREAD

**Issue by Sinled** [rwjblue/ember-cli-template-lint#170]
Sometimes it is useful to run tests without linting, 
but currently addon ignores `nolint` option in tests

or may be i am missing something?

**Comment by rwjblue** [comment]
Depending on version of ember-cli-qunit being used, checking that `nolint` checkbox should work.

**Comment by Sinled** [comment]
@rwjblue 3.0.1

**Comment by rwjblue** [comment]
I believe this should be working properly. Happy to try to dig in if it isn't.
