### ISSUE TITLE
Enforce consistent quote style

### ISSUE THREAD

**Issue by joukevandermaas** [rwjblue/ember-cli-template-lint#25]
Something that plagues our templates is inconsistent quotes. For example, take the following snippets:

```hbs
{{edit-person name="Jessica Jones" changed=(action 'personChanged')}}

<div class="messages">
  {{#each messages as |message|}}
    <span class='message'>{{message}}</span>
  {{/each}}
</div>
```

Similar to the [rules](https://github.com/dockyard/styleguides/blob/master/engineering/javascript.md#strings-1) used in `ember-suave`, it would be great to enforce a consistent quote style across an app.

I personally prefer using double quotes in html/templates, but I think consistency is the most important. This should probably be configurable in order to migrate existing projects easier.

Some examples of what I'd be fine with:

```hbs
{{edit-person name="Jessica Jones" changed=(action "personChanged")}}

<div class="messages">
  {{#each messages as |message|}}
    <span class="message">{{message}}</span>
  {{/each}}
</div>

{{! single quotes are okay, if they contain double quotes }}
{{edit-person name='Zebediah "Purple man" Killgrave' changed=(action "personChanged")}}
```

The error message should contain the exact position of the 'wrong' string, so fixing the error is easy  and editor integration is not broken.

**Comment by rwjblue** [comment]
I just did a quick review of the AST output and it doesn't look like we know if single or double quotes are used. :disappointed:

**Comment by rwjblue** [comment]
I believe that it should be possible to add this information to the AST for our needs, but I'm not sure if there are other ramifications for doing this.  I'll continue digging...

**Comment by rwjblue** [comment]
I did more digging on this, and believe that it is possible by using the `loc` information during walking the AST together along with the known raw source. This is roughly what `Parser.prototype.sourceForMustache` does in [HTMLBars](https://github.com/tildeio/htmlbars/blob/master/packages/htmlbars-syntax/lib/parser.js#L59-L90)/[Glimmer](https://github.com/tildeio/glimmer/blob/master/packages/node_modules/glimmer-syntax/lib/parser.ts#L59-L90).

**Comment by rwjblue** [comment]
Ok, I finally got that done in https://github.com/rwjblue/ember-cli-template-lint/pull/81. It should be possible now to take care of this...

**Comment by oriSomething** [comment]
i think i'll take it from here

**Comment by rwjblue** [comment]
👍

**Comment by rwjblue** [comment]
I'm going to close this issue in favor of the work being done in https://github.com/rwjblue/ember-cli-template-lint/pull/88.
