### ISSUE TITLE
3rd party addons templates are being linted

### ISSUE THREAD

**Issue by arschmitz** [rwjblue/ember-cli-template-lint#252]
templates from 3rd party addons templates are being linted along with the ones in the project. Im specifically seeing this issue with ember-paper

**Comment by rwjblue** [comment]
in general, this only happens when the addon accidentally ships with `isDevelopingAddon() { return true; }` in their `index.js`.

What version of ember-paper are you using?

**Comment by arschmitz** [comment]
im using 1.0.0-alpha.14 which does indeed include that

**Comment by rwjblue** [comment]
The same issue would happen with any app/**/*.js files too, probably best to file an issue over at ember-paper to fix this...

Thanks for confirming this was an issue elsewhere, closing...

**Comment by arschmitz** [comment]
I actually was not having this happen with js linting (ember-cli-standard) or style lint for css (ember-cli-stylelint) not sure why it was only this

**Comment by arschmitz** [comment]
Actually looks like both of these filter addon's out just curious why this does not do the same what is the use case for wanting to lint outside / 3rd party code?

**Comment by rwjblue** [comment]
The better question is why would an addon force this upon you by hard coding `isDevelopingAddon` to return `true`?

**Comment by arschmitz** [comment]
Well that i can't answer since iv never done that in addons iv developed.
