### ISSUE TITLE
Avast gives 'infection blocked' when doing npm i for ember-cli-template-lint

### ISSUE THREAD

**Issue by VincentBons** [rwjblue/ember-cli-template-lint#254]
Each time I npm install ember-cli-template-lint, my anti-virus Avast gives a notification of an infection being blocked. This is on Mac osx. the infection is JS:Downloader-EKT [Tool]. 

Are there more people who have this issue?

**Comment by rwjblue** [comment]
I don't really think there is anything I can do about this.  There certainly are no viruses published in the tarball on npm.

closing for now...
