### ISSUE TITLE
Add rules for deprecated patterns.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-cli-template-lint#28]
As of #27 we are no longer using `ember-template-compiler.js`, so we can now support deprecations across a number of Ember versions.

A few things that jump out are:
- [x] `{{#each foo in bar}}{{/each}}` #84
- [ ] `{{#each foo itemController="asdf" as |bar}}{{/each}}`
- [x] `{{#view 'foo'}}{{/view}}`
- [x] `{{view 'foo'}}`
- [x] `{{view.some.path}}`
- [ ] `{{input on="enter" action="lol"}}`

There are likely more...

**Comment by rwjblue** [comment]
This likely means bringing over the transforms for various Ember versions (1.13 had many more than 2.0 for example).  Some tweaks will be needed from the Ember versions (now that we are not using the Ember provided `ember-template-compiler.js`), like calling `logLintError`.

**Comment by rwjblue** [comment]
Discussed this with @fivetanely yesterday.  I would love to be able to add support for the common set of template deprecations in 1.13, to make it easier for folks to track down (and prevent introducing) issues.

**Comment by rwjblue** [comment]
#84 did a rule for the first item here.  I think the others are ready to be worked on following the pattern in #84....

**Comment by toranb** [comment]
@rwjblue I think your comment above is something that interests me - I've got a 1.13.13 app and added this in hopes of silencing deprecation warnings during compile but I'm starting to think that's not supported in the current build of ember-cli-template-lint.

What is required to silence these at build/compile time for 1.13 or is that not (yet) supported?

Thanks for the great addon!

**Comment by rwjblue** [comment]
ember-cli-template-lint used to be an addon that simply silenced deprecations at build time and "moved" them to be issued during the normal browser test running process.  The last version that had that behavior was [0.1.4](https://github.com/rwjblue/ember-cli-template-lint/tree/v0.1.4), but the functionality was moved into ember-cli-deprecation-workflow directly.  You should be able to use the latest version of that addon for both build time deprecations and browser runtime deprecations.

**BUT** that is not what this issue is about :wink:.  This issue is about adding linting failures for deprecated patterns in templates.

**Comment by toranb** [comment]
@rwjblue ah, great history lesson anyway :) thanks again @rwjblue

**Comment by rwjblue** [comment]
I'm going to close this for now, most of the big ones have already been addressed.  I'm still happy to add more rules for deprecated patterns though if folks have ideas...
