### ISSUE TITLE
Update README to include info that linting occurs during build

### ISSUE THREAD

**Issue by GCheung55** [rwjblue/ember-cli-template-lint#32]
The README doesn't describe when linting occurs. It would be helpful information to include and what kind of error to expect/see.

**Comment by rwjblue** [comment]
:+1: - We are using Ember CLI's `lintTree` hook (which we updated to support linting templates).  Basically, linting runs during the app's build process at roughly the same time as JSHint/ESLint run...

**Comment by rwjblue** [comment]
I'd be happy to review/land a PR for this if you have time. I'm going to close this issue though since it isn't really a bug in the linter per-se...
