### ISSUE TITLE
Should lint everytime ember builds

### ISSUE THREAD

**Issue by urbany** [rwjblue/ember-cli-template-lint#34]
Hi, @rwjblue first of all, thank you so much for all the stuff you do for Ember, awesome work!
I just tried this since it seems like an awesome idea but I'm having trouble seeing the linter output.
Is this supposed to happen?
1. update cli to 2.4.2 and install ember-cli-template-lint@0.2.1
2. ember serve
3. see multiple linter warnings
4. don't fix anything
5. restart ember serve
6. no errors show up (although they are still there)

I even ``rm -rf tmp/ dist/`` and start the server again but nothing shows up. I know the errors are still there because I didn't fix them.
How can I re-lint my files?

Thank you so much in advance!

**Comment by rwjblue** [comment]
As with JSHint, JSCS, and ESLint the warnings only print to the console on the first time each template is processed (we cache aggressively to avoid large build time slow downs). If you run your tests, you should see the linting failures as failed tests.

I do think we can do something about this (make all warnings print on first boot or something), but I need to make some changes upstream in broccoli-persistent-filter first.

**Comment by urbany** [comment]
Print all on first build seems like a good idea to me, but now I'm using the tests to check the lint errors (like you said) so if I was the only one confused by this I think it's ok like it is.

**Comment by rwjblue** [comment]
No, I completely agree with you on this one.  While the `ember test` part is very important, I think the general expectation of folks is that they would see that information in the console during the build.

I submitted https://github.com/stefanpenner/broccoli-persistent-filter/pull/50 to support this upstream.  I spoke with @stefanpenner and we are roughly on the same page (that it is generally good to be able to include these warnings in the console for each build).

**Comment by urbany** [comment]
Working! Thanks a lot @rwjblue
