### ISSUE TITLE
How do I get a list of files that failed to lint?

### ISSUE THREAD

**Issue by khornberg** [rwjblue/ember-cli-template-lint#52]
In the `lintFor` function, is there anyway that this returns a list of templates that failed?

**Comment by rwjblue** [comment]
Hmm, not sure what you mean. What are you trying to do?

**Comment by khornberg** [comment]
I had two ideas. 

2. If a list failed templates is returned then some other code could process that list and try to correct the errors.

1. Related for the first idea, this is my primary motivation. This addon along with ember-cli#5561 proves that one can inspect the templates. If `TemplateLinter` (or maybe it is a separate addon) can return a list of components used in the templates, one could then filter the app tree to include only the used components. Having read the changes in the `ember-cli` PR it seems that another hook would be necessary since, the `lintFor` hook is only operating on the `test` tree. 

Related to the ability to filter based on components used, there may be other criteria that one would want to filter by based on the complied template.

This may be more appropriate as an issue on ember-cli.

**Comment by rwjblue** [comment]
I definitely agree that I need to split this library up and break out a 'ember-template-lint' library that would work somewhat more standalone (my selfish desire here is to get nice Emacs integration showing errors/warnings inline). This separate lib would have an API and likely JSON output that could be used to satisfy item 1 here. 

Item 2 above is already possible without adding additional hooks in ember-cli. Adding an entry in the registry (within the setupPreprocessorRegistry hook) would be able to do exactly this. The trick would be to expose a mechanism to later stages to allow filtering.

**Comment by khornberg** [comment]
Ok. Where would one add the mechanism?

**Comment by rwjblue** [comment]
I'm going to close this for now, see #85 for more details about making the underlying engine more pluggable...
