### ISSUE TITLE
Add acceptance tests

### ISSUE THREAD

**Issue by GavinJoyce** [rwjblue/ember-cli-template-lint#69]
Following on from https://github.com/rwjblue/ember-cli-template-lint/pull/68, I'd like to add some acceptance tests to verify the actual output of templates in the DOM, especially with per-template configuration.

I need to research the reason why further, but it seems that the [`lintTree` hook](https://github.com/ember-cli/ember-cli/blob/88ae6b10b4cfea491972e64bd3dd359c714c8efe/ADDON_HOOKS.md#linttree) in [`index.js`](https://github.com/rwjblue/ember-cli-template-lint/blob/master/index.js) isn't called for the `templates` tree when running the dummy app. It's only called for `app` and `tests`.

TODO:

 * [ ] Upgrade to ember-cli latest

**Comment by GavinJoyce** [comment]
<img width="719" alt="screen shot 2016-04-09 at 23 07 08" src="https://cloud.githubusercontent.com/assets/2526/14406709/d17018c2-fea7-11e5-97a9-c6a8eff945e2.png">

**Comment by rwjblue** [comment]
I think this is done, right?

**Comment by GavinJoyce** [comment]
Yes, thanks!
