### ISSUE TITLE
Rule for triple-curlies.

### ISSUE THREAD

**Issue by nathanhammond** [rwjblue/ember-cli-template-lint#8]
Linter should allow us to disable triple-curlies.

**Comment by rwjblue** [comment]
:+1:

**Comment by rwjblue** [comment]
Created example transform http://jsbin.com/godigi/edit?js,output.

**Comment by halfdan** [comment]
The logic in detectTriple is incorrect - it should be `!node.escaped` instead of `node.escaped`. 

Corrected example: http://jsbin.com/denazipeka/edit?html,js,output

**Comment by rwjblue** [comment]
@halfdan - Good catch, thank you!
