### ISSUE TITLE
Split core into stand alone package. 

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-cli-template-lint#85]
I am working this weekend to split the rules from ember-cli-template-lint into ember-template-lint which has a simple JS API (and is unrelated to ember-cli). This library would then consume that external lib, and work exactly the same as it does today.

This will unlock a number of things:

* Writing the reverse of sourceForNode (ala rewriteNode or something).
* Add a command line invocation (outside of ember-cli land) 
* Use both of those things and add a --fix command to rewrite mechanical refactors (aka {{each foo in bar}} to {{each bar as |foo|}}). This could be used like (or from) ember-watson.

**Comment by oriSomething** [comment]
this thing gon'na be great. when do you plan to start with it?
and i have a suggestion. i'm not sure why on the rules files we export a function that returns a class?
maybe it would be a simpler to change the rules so we just export the class:
```js
var buildPlugin = require('./base');

var LogTripleCurlies = module.exports = buildPlugin('triple-curlies');

LogTripleCurlies.prototype.parseConfig = function(config) {···};

//···
```
the `addonContext` will be added in the `constructor` which not seem to be in used by the plugins anyway, and in ES6 it would be even prettier:

```js
var buildPlugin = require('./base');

module.exports = class LogTripleCurlies extends buildPlugin('triple-curlies') {
  parseConfig(config) {
    //···
  }
};

```

**Comment by rwjblue** [comment]
The current structure is required because of internal details of the AST parsing. Currently, `HTMLBars` / `Glimmer` call `plugin = new Plugin(); plugin.syntax = someSyntaxThing` each time we compile a file.  So the current "return a function that returns a class" thing is needed so that the addon context can be provided (since we can't pass instances to the build config).  

It is definitely possible to fix this, it just hasn't been a super high priority yet...

**Comment by oriSomething** [comment]
i've just said that, because it's a great timing for making API changes.
and for the first question i've asked :) when do you plan to start this project? i'd like to help in what i can

**Comment by rwjblue** [comment]
I am still working on some refactors but the new repo is at https://github.com/rwjblue/ember-template-lint.
