### ISSUE TITLE
Add command to add disable statements to the top of every template.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-cli-template-lint#87]
This would allow a project to begin using ember-cli-template-lint ensuring new templates match the rules chosen in the projects `.template-lintrc.js` file, and allow them to slowing remove the disable comments from each file as they are touched/fixed.

**Comment by oriSomething** [comment]
would it be similar to `/* eslint: comma-dangle: [2, "only-multilines"] */`?
how would like the API to be?

**Comment by rwjblue** [comment]
We already have an API to disable all rules or specific rules per template. This issue is just about adding a command to make it easy to add those comments to all templates in a project at once.

**Comment by rwjblue** [comment]
I replaced this idea with the `pending` concept.  The command added to generate `pending` list is `ember template-lint:print-failing`.
