### ISSUE TITLE
Ensure build failure when linting fails.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-cli-template-lint#9]
This requires updates to ember-cli itself to ensure `lintTree('template'` is called (we should also probably add `lintTree('style'` too).

**Comment by rwjblue** [comment]
WIP PR here https://github.com/ember-cli/ember-cli/pull/5561

**Comment by rwjblue** [comment]
PR in ember-cli landed, should be released in 2.4.2.

**Comment by RedTn** [comment]
Ember still seems to be building when I get a linting error:

> ===== 1 Template Linting Error
cleaning up...
Built project successfully. Stored in "dist/".

Using `"ember-cli-template-lint": "^0.7.5"`

**Comment by RedTn** [comment]
Nevermind! Ember will still build the project if you use "ember b", but using "ember t" will indicate that there was a failure!

**Comment by rwjblue** [comment]
Yep!
